export { Transmission } from './Transmission'
export type { ShiftResult } from './Transmission'
export { GearCalculator } from './GearCalculator'
export { AutomaticTransmission } from './AutomaticTransmission'
export type { AutomaticTransmissionConfig, AutoShiftInput, AutoShiftDecision } from './AutomaticTransmission'
